sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root  # ← 加上这行，注意冒号后面有一个空格！

  alioss:
    endpoint: ${SKY_ALIOSS_ENDPOINT}
    access-key-id: ${SKY_ALIOSS_ID}
    access-key-secret: ${SKY_ALIOSS_SECRET}
    bucket-name: ${SKY_ALIOSS_BUCKET}

  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}

  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    # 👇👇👇 就是这里！加上 -key 👇👇👇
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication